#
# For licensing see accompanying LICENSE file.
# Copyright (C) 2026 Apple Inc. All Rights Reserved.
#
### Adapted from https://github.com/dllm-reasoning/d1 (Apache 2.0)
# ModelConfig
torch_dtype: bfloat16
load_in_4bit: false
model_path: GSAI-ML/LLaDA-8B-Instruct

attn_implementation: flash_attention_2

# GRPOConfig
dataset: gsm8k_and_math
seed: 123
bf16: false

adam_beta1: 0.9
adam_beta2: 0.99
weight_decay: 0.1
max_grad_norm: 0.2

use_vllm: false
vllm_device: auto
vllm_gpu_memory_utilization: 0.9

warmup_steps: 100
logging_steps: 1
learning_rate: 3e-5
lr_scheduler_type: cosine
reward_functions:
  - mixed_correctness_mult_reward_func
  - mixed_correctness_reward_func
reward_weights:
  - 1.0
  - 0.0

num_generations: 8
num_train_epochs: 1

per_device_eval_batch_size: 1
per_device_train_batch_size: 16
gradient_accumulation_steps: 1

gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false

resume_from_checkpoint: false

# Parameters for saving checkpoints
save_steps: 50
save_strategy: steps
save_total_limit: 500

# Diffusion and GRPO-specific
max_completion_length: 256
max_prompt_length: 200
block_length: 32
generation_batch_size: 128
remasking: policy
beta: 0.
epsilon: 0.5
num_iterations: 2
loglikelihood_dtype: float32

# Policy specific
policy_type: dit_confidence
policy_hidden_dim: 128
policy_feedforward_dim: 512
policy_num_heads: 2
policy_num_blocks: 1
policy_dropout: 0.0
policy_time_embed_dim: 128
policy_full_context: true
policy_smart_init: -2.0
